sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t illidan53/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true illidan53/docker-react npm run test
